facebook/bpfilter

README.md
codegen.c

Currently, bpfilter statically defined which interface it's attached to. While this will change in the future, it can be confusing for the users.
Added a comment in the README.md to explain how to change which interface bpfilter is attached to.

README: detail how to change the interface used

---

tests/unit/src/core/context.c
tests/unit/src/core/flavor.c
tests/unit/src/core/helper.c
tests/unit/src/core/hook.c
tests/unit/src/core/list.c
tests/unit/src/core/marsh.c
tests/unit/src/core/target.c
tests/unit/test.h

`TestAssert()` is used to check `assert()` requirements on a function's
paramters: some function require an argument to be non-NULL to behave
properly, `TestAssert()` allows to ensure the function will `assert()` on
this argument's value, to prevent buggy behaviour.
Instead of passing an ID to `TestAssert()` to concatenate to the function
name and allow multiple `TestAssert()` on the same function, use
`__COUNTER__` to automatically assign an ID to the test.

tests: use __COUNTER__ for TestAssert

---

CMakeLists.txt
lib/CMakeLists.txt
resources/bpfilter.pc.in
src/CMakeLists.txt

Add CMake install target to install locally bpfilter daemon, libbpfilter, and headers.
Add bpfilter.pc to use libbpfilter through pkg-config.

Add CMake install target

---

.clang-format
src/core/context.c
src/core/context.h
src/main.c

Transient mode ensure `bpfilter` won't load `/run/bpfilter.blob` at startup, nor will it save its runtime context into `/run/bpfilter.blob`. Additionally, all the generated BPF program will be detached and unloaded when `bpfilter` stops.

Add transient mode

---

.github/workflows/ci.yaml
CMakeLists.txt
README.md
shared/include/bpfilter/shared/helper.h
shared/src/generic.c
src/core/bpf.c
src/core/bpf.h
src/core/btf.c
src/core/btf.h
src/core/counter.h
src/core/flavor.h
src/core/logger.h
src/core/target.c
src/generator/codegen.c
src/generator/program.c
src/generator/program.h
src/generator/reg.h
src/generator/stub.c
src/generator/stub.h
src/generator/tc.c
src/main.c
src/opts.c
src/opts.h
src/xlate/ipt/ipt.c
tests/end_to_end/CMakeLists.txt
tests/end_to_end/end_to_end.py

> A dynamic pointer (struct bpf_dynptr) is a pointer that stores extra metadata
alongside the address it points to. This abstraction is useful in bpf given
that every memory access in a bpf program must be safe. The verifier and bpf
helper functions can use the metadata to enforce safety guarantees for things 
such as dynamically sized strings and kernel heap allocations.
> \- From [[PATCH bpf-next v5 0/6] Dynamic pointers](https://lore.kernel.org/bpf/20220523210712.3641569-1-joannelkoong@gmail.com/)
Until now, `bpfilter` has only supported TC BPF programs, meaning it can freely access the `__sk_buff` argument of the program and the `data` and `data_end` fields. However, not all the BPF program types allow for direct packet access. …

Add support for BPF `dynptr`

---

CMakeLists.txt
resources/bpfilter.pc.in

When building in debug mode, bpfilter (and libbpfilter) is linked to asan and ubsan. However, those link flags are not reflected in `bpfilter.pc`, leading to build failure in downstream projects.
Use a generator expression to add `-fsanitize=address` and `-fsanitize=undefined` to `bpfilter.pc` in debug mode.

Fix `bpfilter.pc` debug link flags

---

README.md

Update README.md with details about a working `bpfilter` configuration (Linux and `libbpf` version) and details kernel version requirements, following #14 .

Update README.md to include required Linux version

---

.clang-format
CMakeLists.txt
doc/CMakeLists.txt
src/core/bpf.c
src/core/bpf.h
src/core/flavor.c
src/core/flavor.h
src/core/hook.c
src/core/hook.h
src/core/target.c
src/external/nf_bpf_link.h
src/generator/codegen.c
src/generator/codegen.h
src/generator/nf.c
src/generator/nf.h
src/generator/program.c
src/generator/program.h
src/generator/stub.c
src/generator/tc.c
src/xlate/ipt/ipt.c
tests/unit/CMakeLists.txt
tests/unit/src/core/hook.c
tests/unit/src/generator/codegen.c
tests/unit/src/generator/nf.c
tests/unit/test.c
tests/unit/test.h

Add a new `NF` flavor to support generation of `BPF_PROG_TYPE_NETFILTER` programs using `bpfilter`. 
Until now, `bpfilter` would generate TC programs for `iptables` (IPT front). Meaning it had to perform a routing table lookup on TC ingress to check whether the `LOCAL_IN` or `FORWARD` filtering rules should be applied to the packet.
This PR add support for `BPF_PROG_TYPE_NETFILTER` programs, giving access to `LOCAL_IN`, `FORWARD, and `LOCAL_OUT` hooks to attach programs to.

Add support for Netfilter BPF programs

---

shared/include/bpfilter/shared/generic.h
src/generator/nf.c
src/generator/program.c
src/generator/program.h
src/main.c
src/opts.c
src/opts.h

This PR contains two different changes, aiming to allow `bpfilter` to be run from a Docker container.
First of all, use `/run/bpfilter` as runtime directory for `bpfilter` instead of `/run`. The serialised data and the socket will now be created in this directory.
Also, even with `--transient` enabled, `bpfilter` would pin the various programs and maps into `/sys/fs/bpf` during runtime (and remove before stopping). This would prevent `bpfilter` to be run with a read-only `/sys/fs/bpf` directory (in a container for example). This change prevent pinning of programs and maps is transient mode is used, and keep the programs and maps file descriptors within `struct bf_program` to ensure we can still access them.

Update `bpfilter` runtime directory and prevent BPF objects pinning on `--transient` run

---

.clang-format
CMakeLists.txt
shared/include/bpfilter/shared/response.h
shared/src/response.c
src/core/bpf.c
src/core/bpf.h
src/core/dump.c
src/core/dump.h
src/core/flavor.c
src/core/flavor.h
src/core/list.h
src/generator/stub.c
src/generator/stub.h
src/generator/tc.c
src/generator/xdp.c
src/generator/xdp.h
src/main.c
src/opts.c
src/opts.h
src/xlate/ipt/ipt.c

Multiple improvements to the codebase derived from `nftables` support:
- Add `bf_dump_hex()` to perform hexdump of a buffer.
- Refactor `bf_list_empty()`.
- Add `bf_response_new_raw()`.
- Add XDP support.
- Add option to disable `iptables` front.

Various improvements

---

README.md
doc/iptables.md

Add doc/iptables.md to document how to build iptables to be used with bpfilter.

doc: document building and usage of iptables with bpfilter

---

src/generator/program.h
src/generator/stub.c

The protocol field in the IPv4 header is 8 bits, not 16.

generator: fix IP header protocol field size

---

src/generator/program.c
tests/unit/CMakeLists.txt
tests/unit/src/generator/program.c

When `bpfilter` emit an instruction, the instructions buffer in the program might be too small. In such a case, `bf_program_grow_img()` is called to grow the buffer size.
`bf_program_emit_fixup_call()` wasn't growing the buffer but returning `-EOVERFLOW` instead, this change fix this behaviour.

generator: grow instructions buffer when `bpfilter emits a fixup call

---

CMakeLists.txt
doc/developers/generation.rst
doc/index.rst
src/generator/jmp.c
src/generator/jmp.h
src/generator/nf.c
src/generator/stub.c
tests/unit/CMakeLists.txt
tests/unit/src/generator/jmp.c

`bpfilter` emits jump instructions to the BPF programs. These jumps are relative to the current instruction pointer. This means that the jump offset need to be carefully updated if the program is generated differently:
```
EMIT(program, BPF_JMP_IMM(BPF_JEQ, BF_REG_2, 0, 2)); EMIT(program,
BPF_MOV64_IMM(BF_REG_RET, program->runtime.ops->get_verdict(
BF_VERDICT_ACCEPT)));
EMIT(program, BPF_EXIT_INSN())
```
The jump instruction is used to jump after the `BPF_EXIT_INSN()` call if if condition is true. However, if any instruction is added before `BPF_EXIT_INSN()`, the jump offset needs to be updated. This type of code prone to error is common in bpfilter for error management.
Local BPF jump contexts are introduced to handle this issue. A context define a scope-bound set of instructions to be …

generator: add support for local BPF jump contexts

---

CMakeLists.txt
doc/developers/generation.rst
src/core/bpf.c
src/core/bpf.h
src/generator/dump.c
src/generator/print.c
src/generator/print.h
src/generator/program.c
src/generator/program.h
src/main.c
tests/unit/CMakeLists.txt
tests/unit/src/generator/print.c

This patch introduces a new set of functions to allow the BPF programs to print messages. The messages are predefined and stored in a BPF map. The BPF programs can then load the map and print the messages using the `bpf_trace_printk()` helper.
A new `EMIT_PRINT()` macro is introduced to emit the BPF instructions to load the map, the message's length, the program's ifindex, hook and front and call `bpf_trace_printk()`.

Logging from bpf programs

---

doc/CMakeLists.txt
doc/todo.rst

`todo.rst` was used to display all the todo defined as Doxygen comment. It's not currently used in the documentation, so it can be removed.

doc: remove `todo.rst`

---

src/core/rule.c
src/core/rule.h
src/generator/program.c
src/xlate/ipt/ipt.c

In order to prepare `bpfilter` for `nftables` support, the rule counter should be optional. `nftables` doesn't add a counter for every rule unless it is explicitly requested.
The counter is enabled by default for `iptables`.

core: make rule counter optional

---

src/generator/codegen.c
src/generator/codegen.h
src/generator/program.c
src/generator/program.h

Introduce `bf_program_update()` and `bf_codegen_update()` to update the bytecode of a `bf_program` and reload it. This change improve support for fast reload of the bytecode, without downtime.

generator: add support for codegen update

---

.github/workflows/ci.yaml
.github/workflows/fork.yaml
CMakeLists.txt
doc/developers/fronts/index.rst
doc/developers/fronts/nftables.rst
doc/index.rst
doc/sources.rst
src/CMakeLists.txt
src/xlate/nft/nfmsg.c
src/xlate/nft/nfmsg.h
tests/unit/CMakeLists.txt
tests/unit/harness/mock.c
tests/unit/harness/mock.h
tests/unit/src/xlate/nft/nfmsg.c

`nftables` uses Netlink to communicate with the kernel. In order to support `nftables` and limit the changes to `nft` itself, `bpfilter` will receive Netlink messages from `nftables`.
This change introduce `bf_nfmsg` as an abstraction over Netfilter-specific Netlink messages.

`nftables` support: add `bf_nfmsg` to represent Netfilter Netlink messages

---

CMakeLists.txt
doc/developers/fronts/nftables.rst
src/xlate/nft/nfgroup.c
src/xlate/nft/nfgroup.h
tests/unit/CMakeLists.txt
tests/unit/harness/helper.c
tests/unit/harness/helper.h
tests/unit/src/xlate/nft/nfgroup.c

Introduce `bf_nfgroup` to abstract Netlink multipart messages. This will be used to return the list of tables/chains/rules/... from `bpfilter` to `nftables`. If completes the `bf_nfmsg` abstraction.

`nftables` support: add `bf_nfgroup` for multipart Netlink messages

---

.github/workflows/pages.yaml

Documentation generation [failed due to a missing dependency](https://github.com/facebook/bpfilter/actions/runs/8008621318/job/21875440115). This commit aims to install that missing dependency for the failing workflow.

Fix documentation generation by installing `libnl3-devel`

---

src/xlate/nft/nfgroup.c
src/xlate/nft/nfgroup.h
src/xlate/nft/nfmsg.c
src/xlate/nft/nfmsg.h
tests/unit/src/xlate/nft/nfgroup.c
tests/unit/src/xlate/nft/nfmsg.c

When a group of Netfilter Netlink messages is converted to a response, the response will contain a multipart message if the group contains more than one message. The NLM_F_MULTI flag will be set on all the messages and a final NLMSG_DONE message will be appended to the response.

xlate: nft: `bf_nfgroup` automatically set `NLM_F_MULTI` flag on multipart messages

---

CMakeLists.txt
lib/include/bpfilter/bpfilter.h
lib/src/nft.c
shared/include/bpfilter/shared/front.h
shared/src/front.c
src/core/hook.c
src/core/hook.h
src/opts.c
src/xlate/front.c
src/xlate/nft/nft.c
tests/unit/CMakeLists.txt
tests/unit/shared/src/front.c
tests/unit/src/opts.c
tests/unit/src/xlate/nft/nft.c

This change is part of a bigger work in progress to support `nftables` with `bpfilter`.
This change introduce the new `nft` front-end, which only supports `nftables`'s `INGRESS` hook. While `libbpfilter` has 2 new functions (`bf_nft_send()` and `bf_nft_sendrecv()`), all the requests will be answered with `-ENOTSUP` from `bpfilter`.
All `--no-nftables` command line option to disable `nftables` support.

Add boilerplate for `nft` front-end for `nftables` support

---

codecov.yml

Some components can't provide good signal from unit tests (e.g. BPF bytecode generation, or front-end/translation layers). This lead to a situation where PR are either merged with failing Codecov check (e.g. because translation code doesn't have the required coverage) and failing CI on the `main` branch, or unit test define solely to fix the coverage issue, without any real value.
This change remove coverage requirement on these components to ensure the Codecov signal is relevant. Later on, different solution could be defined (end-to-end tests, integration tests) to provide coverage signal for those components.

build: remove coverage requirement for code that can't be unit tested

---

doc/sources.rst
src/generator/print.c

Related to #11, update the documentation to clarify that Ubuntu 23.10+ is required.

Fix strings map pinning and detail support Ubuntu version.

---

src/xlate/nft/nft.c

When a counter instruction is discovered within the nft bytecode, it is proceed and the current attribute pointer is updated to the next attribute. However, the next attribute's content is not parsed.
This patch fixes this issue by parsing the next attribute's content when a counter instruction is discovered.

 xlate: nft: fix counter support when translating nft bytecode 

---

src/xlate/nft/nft.c

The warning:
```
In file included from /home/ikruglov/src/bpfilter/src/xlate/nft/nft.c:14:
In function ‘bf_marsh_next_child’,
inlined from ‘_bf_nft_unmarsh’ at /home/ikruglov/src/bpfilter/src/xlate/nft/nft.c:100:21:
/home/ikruglov/src/bpfilter/src/core/marsh.h:114:37: warning: ‘child’ may be used uninitialized [-Wmaybe-uninitialized]
114 |         child ? (struct bf_marsh *)(child->data + child->data_len) :
|                                     ^~~~~
/home/ikruglov/src/bpfilter/src/xlate/nft/nft.c: In function ‘_bf_nft_unmarsh’:
/home/ikruglov/src/bpfilter/src/xlate/nft/nft.c:92:22: note: ‘child’ was declared here
92 |     struct bf_marsh *child;
|                      ^~~~~
```

fix warning: ‘child’ may be used uninitialized

---

doc/build.rst

List required dependencies for nftables and iptables both on Fedora and Ubuntu.

doc: list nftables and iptables build dependencies

---

src/main.c

If `data.bin` (`bpfilter`'s serialized context) is smaller than the size of a `bf_marsh` structure, the daemon will crash as it tries to access `marsh->data_len`.
To prevent this, return an error if less than `sizeof(bf_marsh)` bytes are read.

core: prevent crash if data.bin is smaller than bf_marsh structure

---

doc/overview.rst
src/generator/printer.c
src/generator/printer.h
src/generator/program.c
src/generator/stub.c
src/opts.c
src/opts.h
tests/unit/CMakeLists.txt
tests/unit/harness/mock.c
tests/unit/harness/mock.h
tests/unit/src/generator/printer.c

Add `--debug` to generate the BPF programs in debug mode: failed calls to kfunc or BPF helpers will trigger a call to `bpf_printk()` with a debug message. 
Debug mode is disabled by default to avoid overhead.

Add debug mode

---

src/generator/printer.h
tests/unit/CMakeLists.txt
tests/unit/harness/filter.c
tests/unit/harness/filter.h
tests/unit/harness/main.c
tests/unit/harness/opts.c
tests/unit/harness/opts.h

Introduce `--group` (`-g`) command line option support to filter test groups to be run when executing the unit tests. A test group is usually a complete source file of tests.
This change allows for more targeted test execution: it provides a clearer output and faster tests run, leading to simpler development feedback loop.

tests: add `--group` command line option to filter test groups

---

CMakeLists.txt
doc/developers/packets_processing.rst
doc/index.rst
src/core/matcher.c
src/core/matcher.h
tests/unit/CMakeLists.txt
tests/unit/src/core/matcher.c

Currently, rules contains a fixed set of criteria to match the network,packets against: source/destination IP addresses, source/destination ports, ... Adding new criteria to match the packets against would only grow the complexity higher and bloat the `bf_rule` structure, keeping in might that chances are low that all the criteria a used in the same rule, leading to a lot of unused fields.
Instead, a solution is to define packet matching criteria differently, that's what this change is about: bf_matcher are used to define how to match bytes from the network packet according to a reference value, they're composed of:
- A type defining which protocol/field of the network packet the matcher is to be compared to.
- An operator, defining how to compare the network packet data to the reference …

core: introduce `bf_matcher` structure

---

src/core/rule.c
src/core/rule.h
tests/unit/CMakeLists.txt
tests/unit/src/core/rule.c

Add a new field in `bf_rule`: `matchers`, which is a list of `bf_matcher` object. `bf_matcher` are expected to replace specific individual packet matching criteria in `bf_rule`.

core: rule: add support for `bf_matcher`

---

src/core/context.c
src/core/dump.h
src/core/matcher.c
src/core/rule.c
src/generator/codegen.c
src/generator/fixup.c
src/generator/fixup.h
src/generator/printer.c
src/generator/printer.h
src/generator/program.c
src/main.c
src/xlate/nft/nft.c

- Dump `bf_printer` on `bf_context_dump()`
- Do not restore the `bf_printer` map FD if it doesn't exist
- In `bf_program`, dump the fixups and the runtime-only fields, so the full object is dumped
- Add details to the container of dumped objects (e.g. `bf_list<$TYPE>[$SIZE]`)
- Add missing `bf_prefix_pop()` in `bf_rule_dump()`
- Always dump `bf_context`, whether it's been created from scratch or restored (even in transient mode)
- Assert pointer arguments of `*_dump()` functions
- Define `EMPTY_PREFIX` to act as an empty prefix for `*_dump()` function, remove the need for `NULL` check and creation of an empty prefix.

Cleanup `*_dump()` function (and other minor fixes)

---

src/core/matcher.c
src/core/matcher.h
src/core/rule.c
src/core/rule.h
src/xlate/ipt/ipt.c
src/xlate/nft/nft.c

Add missing matchers types and operators, and convert the filtering rules coming from `iptables` and `nftables` into `bf_matcher`. Existing matching criteria are still used (e.g. `bf_rule.src`) as the `bf_matcher` are not yet used to create the BPF bytecode.

Fill `bf_rule`'s matchers from `ipt` and `nft` front-ends

---

CMakeLists.txt
src/core/matcher.c
src/core/matcher.h
src/generator/matcher/ip.c
src/generator/matcher/ip.h
src/generator/program.c

Generate a rule's bytecode using `bf_rule.matchers` (`bf_matcher` objects) instead of the matching criteria defined in the rule.
The "old" matching criteria remain in the `bf_rule` structure and are still set during front-end translation, but they will be deleted in a subsequent commit.

 generator: matcher: use `bf_matcher` to create the BPF bytecode

---

doc/build.rst

Ubuntu 22.04 can't be used to build bpfilter, even though its HWE stack allows for Linux 6.5 to be installed: kernel headers used to build kernel modules are updated to 6.5, but the system headers, used by userspace application, remain in v5.15.

doc: clarify Ubuntu 22.04 LTW HWE situation

---

.github/workflows/ci.yaml
.github/workflows/fork.yaml
.github/workflows/pages.yaml

Run CI on Ubuntu 24.04 and Fedora 40, in addition to existing distros. Use Fedora 40 as default runner.

build: add Ubuntu 24.04 and Fedora 40 to CI

---

CMakeLists.txt
doc/developers/generation.rst
src/generator/matcher/ip.c
src/generator/nf.c
src/generator/program.h
src/generator/stub.c
src/generator/stub.h
src/generator/swich.c
src/generator/swich.h
src/generator/tc.c
src/generator/xdp.c
tests/unit/CMakeLists.txt
tests/unit/src/generator/swich.c

This PR refactors the generation of the bytecode used to parse a packet's content, in order to prepare for the program's matchers to be used. It consists in:
- Introduce `bf_swich` to emulate a switch-like functionality in BPF bytecode (with doc and unit tests).
- Refactor packet pre-processing: uses `bf_swich` to simplify protocol detection, reorder instructions for more clarity.
- Reorder and cleanup pre-processed packet data located in the runtime context

Refactor the generation of the bytecode to parse and detect a packet's protocols

---

src/core/context.c
src/core/dump.h
tests/unit/harness/cmocka.h
tests/unit/src/core/btf.c
tests/unit/src/core/helper.c
tests/unit/src/core/list.c
tests/unit/src/core/marsh.c
tests/unit/src/core/matcher.c
tests/unit/src/core/rule.c
tests/unit/src/generator/printer.c
tests/unit/src/generator/swich.c
tests/unit/src/opts.c
tests/unit/src/xlate/nft/nfmsg.c

Shorten `assert_int_not_equal(0, xxx())` with `assert_error(xxx())` and `assert_int_equal(0, xxx())` with `assert_success(xxx())`.

Add `assert_success()` and `assert_error()` to check a function's return value

---

doc/build.rst
src/core/bpf.c
src/core/bpf.h
src/core/flavor.h
src/core/hook.c
src/generator/codegen.c
src/generator/codegen.h
src/generator/matcher/ip.c
src/generator/nf.c
src/generator/program.c
src/generator/program.h
src/generator/tc.c
src/generator/tc.h
src/generator/xdp.c
src/xlate/ipt/ipt.c
src/xlate/nft/nft.c
tests/unit/src/core/hook.c

Update the `bf_flavor_ops` to simplify program loading and attachment to the BPF hooks. TC and XDP now use BPF link and `BPF_LINK_UPDATE` to attach and update an existing program. For `BPF_NETFILTER`, the program update logic is handle in `attach_prog` to, but slightly differently as it doesn't support `BPF_LINK_UPDATE`.
The generation and program management logic in `codegen.c` and `program.c` has been simplified to provide to main paths:
- `bf_codegen_up()`: create the `bf_program` objects for a given `bf_codegen`, generate the BPF bytecode and attach the programs to the system.
- `bf_codegen_update()`: update the bytecode of existing BPF programs, and attach them to the system, replacing the out-of-date version of the same program.
This updated logic makes the daemon's workflow simpler …

Refactor program management

---

src/cli/lexer.l
src/cli/parser.y
src/generator/matcher/ip.c

Allow `ip.saddr` and `ip.daddr` to be used in `bfcli` to filter based on source or destination IP, such as:
ip.(s|d)addr (!)$IP(/$MASK)
`!` is optional before the IP address to inverse the match: `ip.saddr 192.168.1.1` will match every packet with source address `192.168.1.1`, while `ip.saddr !192.168.1.1` will match packet without the source address `192.168.1.1` (packet from every other address that is).
Fix IPv4 address filtering bytecode generation by inserting `JMP32` instead of `JMP` for address comparison.

 matcher: ip: support `ip.(s|d)addr` in `bfcli`

---

src/CMakeLists.txt
src/cli/lexer.l
src/cli/parser.y
src/core/matcher.c
src/core/matcher.h
src/generator/matcher/tcp.c
src/generator/matcher/tcp.h
src/generator/matcher/udp.c
src/generator/matcher/udp.h
src/generator/program.c
src/shared/helper.h
src/xlate/cli.c

Add matcher support to filter packets based on source and/or destination port in TCP and UDP. `bfcli` has been updated to allow those new matchers to be used, for example:
- Block SSH: `tcp.dport 22`
- Block outgoing DNS requests: `udp.dport 53`
Fix a memory leak in the `xlate/cli` when the rules are updated.

TCP and UDP source/destination port filtering

---

src/cli/lexer.l
src/cli/parser.y
src/core/matcher.c
src/core/matcher.h
src/generator/matcher/ip.c
src/generator/matcher/tcp.c
src/generator/matcher/udp.c
src/generator/program.c
src/generator/program.h
src/generator/stub.c

Introduce support for TCP flags filtering in `bpfilter`:
- Allow a specific operator to be specified in the `bfcli` rule (`ip.saddr eq 192.168.1.1`, `ip.saddr not 192.168.1.1`).
- Add support for 2 new operators: `any` and `all` (see commit for details).
- Add support for `tcp.flags` matcher: match a rule based on the packet's TCP flags.
Extra changes:
- Add support for `not` operator in `ip.proto`: `ip.proto not icmp`.
- Fix `iphdr.protocol` size: uses 1 byte instead of 2 bytes. This change resolves a verifier complain.

TCP flags filtering

---

CMakeLists.txt
src/CMakeLists.txt
src/core/context.c
src/core/context.h
src/daemon.c
src/generator/nf.c
src/generator/printer.c
src/generator/printer.h
src/generator/program.c
src/generator/program.h
src/xlate/ipt/ipt.c
tests/integration/CMakeLists.txt
tests/unit/src/generator/printer.c

Someone reached out regarding `iptables`' front-end for `bpfilter` because the following command doesn't seem to block packets as expected (tested with `dig +short google.ch @1.1.1.1`):
```shell
iptables -I INPUT --bpf -p udp -j DROP
```
The `iptables` front-end has been let down a bit over the past weeks, this PR aims to fix this specific issue and make the support for `iptables` more stable (amongst a few other issues found during this process). Here's a list of changes:
- Ensure `libbpfilter.so` and `libbpfilter.a` are build with `-fPIC`, while `lib` and `shared` modules used in the daemon are not.
- Fix `nftables` and `iptables` build following the reorganization of the sources tree.
- In `xlate/ipt`, `ip.proto` matcher should have an 8-bits payload, not 16-bits.
- Manually set …

Fix `iptables` protocol filtering

---

.github/workflows/ci.yaml
README.md
doc/developers/build.rst
src/core/hook.c

Ubuntu 23.10 (https://endoflife.date/ubuntu) and Fedora 38 (https://endoflife.date/fedora) are EOL. I missed this information the last time I updated the documentation, but it's not worth maintaining bpfilter for those distributions.
I don't expect anyone to use bpfilter on those systems, so it's better to drop them now than later. Eventually, bpfilter can be build and run on those, but they're not officially supported.

build: drop support for Fedora 38 and Ubuntu 23.10

---

src/cli/cli.c
src/cli/lexer.l
src/cli/parser.y
src/daemon.c
src/generator/matcher/ip6.c
tests/bpf/xdp_printk.bpf.c
tests/bpf/xdp_printk.c

Pretty much what is described in the title, see commits for more details.

Add missing copyright headers, fix `clang-format` errors, enable mask support for `ip6.(s|d)ddr`

---

README.md
doc/_templates/page.html

- Change `page.html` to extend `furo/base.html`, not `furo/page.html`. This prevents the `bpfilter` website's pages from being duplicated.
- Configure the logo in `README.md` to follow the user's color mode.

Documentation improvements

---

doc/usage.rst

The hooks have been renamed in 17dfeae, but the "usage" page of the documentation still uses the old names. Update it.

doc: update the list of hooks in the documentation

---

src/bpfilter/cgen/program.c
src/bpfilter/cgen/stub.c
src/bpfilter/cgen/stub.h

The runtime context used by the BPF programs is filled with zero at the very beginning to ensure no garbage value is used. However, the verifier wouldn't allow for a read to happen before a write, meaning it will prevent us from reading garbage value. Hence, it's better to not zero-out the runtime context.

cgen: do not zero the runtime context

---

doc/usage/bfcli.rst
src/bfcli/lexer.l
src/bfcli/parser.y
src/bpfilter/cgen/matcher/meta.c
src/bpfilter/cgen/nf.c
src/bpfilter/cgen/program.c
src/bpfilter/cgen/program.h
src/bpfilter/cgen/tc.c
src/bpfilter/cgen/xdp.c
src/core/matcher.c
src/core/matcher.h
tests/rules.bpfilter

Interface index filtering doesn't work for XDP/TC, and is a badly implemented for `BPF_NETFILTER` programs. This PR improves the situation by creating a dedicated `ifindex` matcher. 
The behaviour of the matcher depends on the location of the hook: a hook located on the RX path will filter on the ingress interface, while a hook located on the TX path will filter on the egress interface.

Support for interface index filtering

---

src/bpfilter/cgen/cgen.c
src/bpfilter/cgen/nf.c
src/bpfilter/cgen/prog/map.c
src/bpfilter/cgen/prog/map.h
src/bpfilter/cgen/program.c
src/core/marsh.h
tests/unit/src/bpfilter/cgen/cgen.c
tests/unit/src/bpfilter/cgen/prog/map.c

- Decouple the BPF map creation and pinning.
- Fix `BPF_NETFILTER` program update for pinned programs.
- Add function to check if a `bf_marsh` object is empty.

Some bug fixes!

---

src/bpfilter/xlate/ipt/ipt.c
src/core/rule.c
src/core/rule.h
tests/unit/harness/helper.c
tests/unit/src/core/rule.c

`struct bf_rule` doesn't need to contain an interface index field anymore as a dedicated matcher type exists. Remove every reference to `bf_rule.ifindex` and create a matcher of type `BF_MATCHER_META_IFINDEX` from `ipt` front-end.

core: rule: remove `ifindex` field from `struct bf_rule`

---

src/bpfilter/cgen/nf.c
src/bpfilter/cgen/prog/map.c
src/bpfilter/cgen/prog/map.h
src/bpfilter/cgen/stub.h

`clang-tidy` on Fedora 39 noticed some headers are not directly used. Fix the warnings by removing the `#include` directive for those headers.

tests: fix `clang-tidy` warnings

---

src/core/chain.c
src/core/set.c

Fix a few errors when dumping `bf_chain` and `bf_set`. See commits for more details.

Fix dump misprints for chain and set

---

doc/usage/bfcli.rst
src/bfcli/lexer.l
src/bfcli/parser.y
src/bpfilter/CMakeLists.txt
src/bpfilter/cgen/cgroup.c
src/bpfilter/cgen/cgroup.h
src/bpfilter/cgen/nf.c
src/bpfilter/cgen/program.c
src/bpfilter/ctx.c
src/core/bpf.c
src/core/bpf.h
src/core/chain.c
src/core/flavor.c
src/core/flavor.h
src/core/hook.c
src/core/hook.h
tests/bpf/CMakeLists.txt
tests/bpf/cgroup_skb_ingress.bpf.c
tests/bpf/cgroup_skb_ingress.c
tests/bpf/cgroup_skb_ingress.h
tests/rules.bpfilter

This PR introduces support for cgroup hooks in `bpfilter` (using `bfcli`):
- Add a new flavour. cgroup BPF programs are a mix between TC and BPF_NETFILTER programs: they accept `struct __sk_buff`, but they don't have access to the L2 header, and return codes are 0 to drop and 1 to accept.
- Add `bf_bpf_cgroup_link_create()` to create a cgroup link, atomic update of the program is supported. A file descriptor to the cgroup (`open(..., O_DIRECTORY)`) defines which cgroup to attach the program to.
- Add new `cgroup` hook option, only valid for cgroup hooks.
A few other things have been fixed/improved on the way:
- Fix IPv6 support for BPF_NETFILTER program: `AF_INET` was recognized but not `AF_INET6`, this is now fixed.
- Allow a chain defined in `bfcli` to be empty. A empty chain will only …

Add support for `cgroup_skb/ingress` and `cgroup_skb/egress`

---

src/bpfilter/ctx.c

Callback to get a `BPF_NETFILTER` cgen from the context should call `bf_list_node_get_data(node)`, not `bf_list_node_get_data(node->data)`.

ctx: fix invalid pointer access

---

doc/usage/daemon.rst
src/bpfilter/cgen/program.c
src/bpfilter/cgen/stub.c
src/core/bpf.c
src/core/dump.c
src/core/logger.h
src/core/opts.c
src/core/opts.h

Currently, 2 options are available to adjust the verbosity of bpfilter:
- `--verbose`: if set, log `bf_dbg()` messages
- `--debug`: if set, insert debug log message on kfunc failure in the BPF programs.
Those options are confusing (even I can't remember which option is which).
This change removes `--debug` and define flags for `--verbose` to specific which type of debug to be enabled. `--verbose $TYPE` can be used more than once to enable different types of debugging.

core: opts: make verbosity more granular

---

doc/usage/bfcli.rst
src/bpfilter/cgen/cgroup.c
src/bpfilter/cgen/nf.c
src/bpfilter/cgen/tc.c
src/bpfilter/cgen/xdp.c
src/core/chain.c
src/core/hook.c
src/core/hook.h
tests/rules.bpfilter

The custom chain name will be used as the name of the BPF program, making the program easier to find, especially in `--transient` configuration.
For now, only the program name is modified:
- Map names: the chain name is at most `BPF_OBJ_NAME_LEN` characters, if the full length is used there is no room to use a custom prefix for each map, making them indistinguishable.
- Pin path: a chain name can be reused multiple time, but a pin path must be unique.

core: hook: add option to set the chain's name

---

doc/usage/bfcli.rst

The column contains the hook options' values is named "Supported hooks", while it should be "Supported values".

doc: rename hook option column

---

src/bfcli/parser.y

Factorize the chain creation by defining only one production in which the `raw_hook_opts` token can be `NULL`.

bfcli: allow a `raw_hook_opts` token to be `NULL`

---

doc/usage/bfcli.rst
src/bpfilter/cgen/cgroup.c
src/bpfilter/cgen/nf.c
src/bpfilter/cgen/program.c
src/bpfilter/cgen/program.h
src/bpfilter/cgen/tc.c
src/bpfilter/cgen/xdp.c
src/core/chain.c
src/core/hook.c
src/core/hook.h
tests/rules.bpfilter

By default, the chain is loaded and attached to the kernel, but eventually the user don't want the chain to be attached. Hence, by setting the chain option `attach=no`, bpfilter will generate the BPF program, load it (and all the required maps), then stop there. The user is free to open an FD to the program and manipulate it.

cgen: hook: add new `attach` hook option

---

src/core/matcher.c

`matcher.len` was deserialized by reading the size of `matcher.op`, which would lead to erroneous values.

core: matcher: fix `matcher.len` deserialization size

---

CMakeLists.txt
tests/CMakeLists.txt
tests/benchmark/CMakeLists.txt
tests/benchmark/benchmark.cpp

Add a benchmark runner and set `make benchmark` as the target to run it.
The benchmark defines a few classes to ease running the daemon and using bfcli to setup the filtering rules. Only 1 benchmark it defined now as as PoC.
Eventually, the benchmark should output the results in a file so we could compare two different releases.
The benchmark depends on Google Benchmark library. By default, it is disabled so CMake won't look for it. This doesn't change the dependencies required to build bpfilter.

tests: add benchmark

---

tests/benchmark/CMakeLists.txt
tests/benchmark/benchmark.cpp

Add support for `--output` option to the benchmark, so the results can be written in JSON to a file. The `make benchmark` target defined in CMake uses this option, so benchmark results can be compared from a commit to another.

tests: benchmark: write results to a JSON file

---

tests/benchmark/CMakeLists.txt

Define a fake dependency to the custom command used to get Git infos. As CMake run the custom commands when a dependency is missing, not creating this fake file will ensure the command is always run and gitrev.txt is always up-to-date.

tests: benchmark: ensure `gitrev.txt` is always up-to-date

---

.clang-format
.clang-tidy
tests/CMakeLists.txt
tests/benchmark/CMakeLists.txt
tests/benchmark/benchmark.cpp
tests/benchmark/benchmark.hpp
tests/benchmark/main.cpp

Extract all the benchmark boilerplate from the main file to move it all into a dedicated source file and add a benchmark to match the packet after X non-matching rules.

tests: benchmark: extract benchmark boilerplate for easier reuse and add benchmark

---

tests/benchmark/benchmark.cpp
tests/benchmark/benchmark.hpp
tests/benchmark/main.cpp

Two simple changes to the benchmarks:
- Reduce the number of `dropAfterXRules` tests
- Record the number of instructions for each generated program to validate size increase overtime

Benchmark improvements

---

.clang-tidy
doc/CMakeLists.txt
doc/Doxyfile.in
doc/usage/daemon.rst
src/bpfilter/CMakeLists.txt
src/bpfilter/cgen/dump.c
src/bpfilter/cgen/dump.h
src/bpfilter/cgen/program.c
src/core/btf.c
src/core/btf.h
src/core/opts.c
src/core/opts.h
src/external/disasm.c
src/external/disasm.h

The current logic used to dump a program's BPF bytecode is unstable. Not all the instructions are supported, and some of them are erroneously printed. However, this logic is not used often (even if it's been proven very useful sometimes) and the amount of effort required to dump the bytecode properly might not be worth the results.
Instead, this PR completely refactor the bytecode dump logic by using [Linux's `disasm.c`](https://github.com/torvalds/linux/blob/master/kernel/bpf/disasm.c), similarly to [`bpftool`](https://github.com/libbpf/bpftool). This change is also inspired by `bpftool`'s dump logic.
A new verbose flag has been added to the daemon to dump a program's bytecode before it is loaded into the kernel.

Improve BPF bytecode dump

---

.clang-tidy
src/bpfilter/cgen/cgroup.c
src/bpfilter/cgen/nf.c
src/bpfilter/cgen/program.c
src/bpfilter/cgen/stub.c

`bpfilter` only supports specific protocols for each layer: IPv4 and IPv6 on L3, TCP/UDP/ICMP on L4. This means we need to decide how to handle packets using other protocols, especially during pre-processing. 
For now, not much decision has been made on this matter: during pre-processing, if an unsupported protocol is discovered, the packet is accepted. This is far from an acceptable behaviour. 
The solution implemented in this PR is to rely on the program runtime context's `l3_proto` and `l4_proto` fields:
- Initialize `l3_proto` and `l4_proto` with 0
- When the L3 header is preprocessed, read `l3_proto`:
- If it is set, create the slice and process the layer (i.e. store `l4_proto` in the context)
- If it is not set, the L3 pre-processing completely
- Repeat for L4 preprocessing
This …

Handle unsupported protocols

---

src/bpfilter/cgen/stub.c

PR #143 introduced two bugs making the program rejected by the BPF verifier:
- The stub function to parse the L4 header reads `l4_proto` as `uint16_t` while it is a `uint8_t`.
- Explicitly write 0 to `l3_proto` and `l4_proto` if the protocol is unknown (or unsupported).

Fix bugs introduced by #143 (Handle unsupported protocols)

---

doc/usage/bfcli.rst
src/bfcli/lexer.l
src/bfcli/parser.y
src/bpfilter/cgen/matcher/tcp.c
src/bpfilter/cgen/matcher/udp.c
src/core/matcher.c
src/core/matcher.h
tests/rules.bpfilter

Add a new matcher operator for ranges used as `$START-$END` and add support for it for TCP and UDP port (source and destination).

core: matcher: add range matcher for TCP and UDP ports

---

doc/usage/bfcli.rst
src/bfcli/lexer.l
src/bfcli/parser.y
src/bpfilter/cgen/cgroup.c
src/bpfilter/cgen/nf.c
src/bpfilter/cgen/program.c
src/bpfilter/cgen/tc.c
src/bpfilter/cgen/xdp.c
src/bpfilter/xlate/nft/nft.c
src/core/chain.c
src/core/flavor.h
src/core/verdict.c
src/core/verdict.h
tests/rules.bpfilter
tests/unit/src/bpfilter/cgen/cgen.c

This PR adds a CONTINUE verdict for rules s.t. a rule can match and continue processing. This allows multiple rules to match and count a packet.
Note CONTINUE is not supported for chains as there is no nesting of chains and one cannot jump between BPF programs.

Add CONTINUE verdict

---

src/bfcli/main.c
tests/benchmark/benchmark.cpp
tests/benchmark/benchmark.hpp
tests/benchmark/main.cpp

Update the benchmark's command line options to support ad-hoc benchmark to be run. Ad-hoc benchmark allows users to define a filtering rule from the command line and benchmark the generated BPF program. The predefined benchmarks defined in `tests/benchmark/main.cpp` will be skipped.

Add support for ad-hoc benchmarks

---

src/bfcli/lexer.l
src/bpfilter/cgen/dump.c
src/libbpfilter/generic.c

- Return the error code when `bf_send()` fails.
- Ignore commas in chain options list.
- Count double instructions as two instructions to ensure the counter is accurate.

A few fixes to `libbpfilter`, `bpfilter`, and `bfcli`

---

doc/CMakeLists.txt
doc/Doxyfile.in
doc/developers/tests.rst
doc/index.rst
tests/CMakeLists.txt
tests/harness/CMakeLists.txt
tests/harness/daemon.c
tests/harness/daemon.h
tests/harness/filters.c
tests/harness/filters.h
tests/harness/process.c
tests/harness/process.h

`make benchmark` uses a testing harness in C++ to run and communicate with the `bpfilter` daemon and `bfcli`. The harness needs to be written in C to perform end-to-end tests using CMocka (which is used for unit tests already).
This PR introduces `tests/harness` to centralize the testing harness for the unit tests, end-to-end tests, benchmark... The document has been updated with the detail of the API. More changes will come to introduce end-to-end testing, and move the benchmark away from the deprecated C++ harness.

Refactor testing harness

---

.clang-tidy

PR154 adds support for the error counter. An enum has been defined to refer to special counters, using negative values to prevent overlap with actual rule counters (with an index > 0). We don't create an enum value for every possible rule counter index, so clang-tidy will complain if we use an enum value with an actual rule counter as the value is not defined in the enum.
Because we use an enum type with non-defined values, clang-tidy complains. This behavior is expected, so the check is disabled.

tests: disable clang-tidy's `clang-analyzer-optin.core.EnumCastOutOfRange`

---

src/bpfilter/cgen/cgen.c
src/bpfilter/cgen/cgen.h
src/bpfilter/cgen/program.c
src/bpfilter/cgen/stub.c
src/bpfilter/xlate/ipt/ipt.c

For kfunc call errors, add a dedicated counter that can be read by the daemon in the future. This counter is exposed implicitly as a named counter object ("errors") via `nft`.
Fixes #105

cgen: add an error counter

---

tests/benchmark/benchmark.hpp

Initializing the `std::optional<std::string>` adhoc rule variable to `""` will... insert a value into the optional! Removing the point of using an optional and running the adhoc benchmark **every time**. Do not initialize the optional.

tests: benchmark: do not initialize the adhoc rule

---

src/bfcli/parser.y
src/bpfilter/CMakeLists.txt
src/bpfilter/cgen/cgen.c
src/bpfilter/cgen/matcher/set.c
src/bpfilter/cgen/matcher/set.h
src/bpfilter/cgen/program.c
src/bpfilter/cgen/xdp.c
src/core/matcher.c
src/core/matcher.h
src/core/set.c
src/core/set.h
tests/e2e/CMakeLists.txt
tests/e2e/genpkts.py
tests/e2e/main.c
tests/harness/CMakeLists.txt
tests/harness/filters.c
tests/harness/filters.h
tests/harness/process.c

Those sets are required for benchmarking purpose until a better solution is available (generic sets). This change adds support for sets using `src IPv6, src port` and `src IPv6` as keys.

Add support for `src IPv6, src port` and `src IPv6` sets

---

CMakeLists.txt
doc/developers/build.rst
doc/developers/tests.rst
tests/CMakeLists.txt
tests/benchmark/CMakeLists.txt

`-DWITH_BENCHMARK=on` will ensure CMake generates a build configuration with the benchmarks enabled.

build: document the `-DWITH_BENCHMARK` option to enable benchmarks

---

tests/benchmark/benchmark.cpp
tests/e2e/CMakeLists.txt
tests/harness/prog.c

- Properly process `bf_cli_set_chain()` error in `bf_test_prog_get()`
- Disable PIC for integration tests, similarly to unit tests
- Use the new `bfcli` command format in the benchmark

A few minor fixes to the tests

---

src/bpfilter/cgen/matcher/ip6.c

Cast bytes to uint32_t in _bf_make32 (used for IPv6 matchers) to avoid overflow.

cgen: matcher: probably cast IPv6 addr single bytes to prevent overflow

---

src/bfcli/main.c
src/bpfilter/cgen/matcher/ip6.c
tests/benchmark/main.cpp

- Return the correct error values from `_bf_do_ruleset_set()`
- Generate unique rules for `dropAfterXRules` to prevent the verifier from removing unused instructions

Fix the benchmark

---

tests/benchmark/benchmark.cpp
tests/benchmark/benchmark.hpp
tests/benchmark/main.cpp

Two changes to the benchmark:
- Add `--no-daemon` option so the benchmark doesn't start the `bpfilter` daemon itself (useful to control the daemon options easily and access the logs).
- Divide the program size fetched from the kernel by `sizeof(struct bpf_insn)` to have the current number of instructions. Use `xlated_prog_len` instead of `jited_prog_len`.

Improvements to the benchmark

---

.github/workflows/ci.yaml
tests/benchmark/CMakeLists.txt
tests/benchmark/asroot

Use `sudo` for the benchmark run if the current user is not root, otherwise run as-is. This is expected to solve the CI build failure as the container waits for a password to be provided with sudo.

Use `sudo` for `make benchmark` if current user is not root

---

src/bpfilter/cgen/cgen.c

On bf_cgen_update(), the codegen is dumped (if verbose is enabled) very early in the function, meaning the old (to be replaced) chain is printed.
Dump the codegen at the end of the function, when the chain replacement occurred, so the new chain is printed.

cgen: dump the codegen after it has been updated

---

src/bfcli/parser.y
src/core/bpf.c

- Fix typo in parser expecting ICMPv6 to be named `icmp6`: filtering on ICMPv6 is now `meta.l4_proto eq icmpv6` as documented.
- Attach Netfilter programs with packet family `NFPROTO_INET` instead of `NFPROTO_IPV4` to filter both IPv4 and IPv6 traffic.

Fix filtering ICMPv6 using `BF_HOOK_NF_LOCAL_IN`

---

src/bpfilter/CMakeLists.txt
src/bpfilter/cgen/cgroup.c
src/bpfilter/cgen/nf.c
src/bpfilter/cgen/prog/link.c
src/bpfilter/cgen/prog/link.h
src/bpfilter/cgen/prog/map.c
src/bpfilter/cgen/program.c
src/bpfilter/cgen/program.h
src/bpfilter/cgen/tc.c
src/bpfilter/cgen/xdp.c
src/bpfilter/xlate/ipt/ipt.c
src/core/bpf.c
src/core/bpf.h
src/core/chain.c
src/core/chain.h
src/core/flavor.h
src/core/hook.c
tests/harness/filters.c
tests/harness/filters.h
tests/harness/prog.c
tools/benchmarks/benchmark.cpp

BPF Netfilter hooks [do not allow `NFPROTO_INET`](https://elixir.bootlin.com/linux/v6.13.3/source/net/netfilter/nf_bpf_link.c#L184) packet family to be used. Hence, a `bpfilter` program can not filter on both IPv4 and IPv6 traffic at once. This PR aims to resolve this to ensure Netfilter programs behave similarly to XDP, TC, and cgroup programs.
The core of this PR is the change to `bf_program` to allow multiple BPF links to be created for a single program. In details:
- Ensure `bf_cgen` structures are not erroneously freed during chain creation (fix #218)
- Add missing attach type for `BF_HOOK_NF_PRE_ROUTING` and `BF_HOOK_NF_POST_ROUTING` (fix #211)
- Update the `ipt` front-end to use chains instead of codegen structure (making chains update easier)
- Introduce the `bf_link` object to …

Allow a program to be attached to multiple hooks

---

src/bpfilter/cgen/prog/link.c
src/bpfilter/cgen/prog/map.c
src/bpfilter/cgen/program.c

GCC complains about `snprintf()` usage if the format string doesn't contain any format argument. This warning is turned into an error when creating the package.

cgen: copy BPF object names using `strncpy()` instead of `snprintf()`

---

CMakeLists.txt

By default, if the current project version can't be deduced from the Git history, the project will use 0.0.0. This can cause issues when building the RPM package as it uses a tarball instead of the repository, meaning there is no Git history.
DEFAULT_PROJECT_VERSION can be set from the command line to define the version of the project.

build: allow `DEFAULT_PROJECT_VERSION` to be set

---

doc/CMakeLists.txt
doc/benchreport

The benchmark report published on [bpfilter.io/external/benchmarks](https://bpfilter.io/external/benchmarks/index.html) doesn't provide details about the commits. This is due to the hardcoded path to the sources directory in `benchreport`. Because the path is invalid on the CI machine, `benchreport` could not find the Git history. Make the path configurable so it is defined based on `CMAKE_SOURCE_DIR`.

Fix `benchreport` commit details

---

src/core/list.c
src/core/list.h
tests/unit/core/list.c

The `bf_list_ops` structure attached to a `bf_list` object contains callbacks to free and marsh a node's data. Occasionally, the data should not be freed, in which case the user needs to set the free callback to a noop function.
Instead, allows `bf_list_ops` to contain `NULL` pointers for the free and marsh callbacks: if the free callback is missing, the node's data is not freed, if the marsh callback is missing, the node's data is not serialized.
`bf_list_new()` and `bf_list_init()` allow for the `bf_list_ops` argument to be `NULL`, in which case they will initialise the list's `bf_list_ops with` a `NULL` free and marsh pointers.
Introduce two convenience macros to define a new list and a new list ops: `bf_list_default(free_cb, marsh_cb)` and `bf_list_ops_default(free_cb, marsh_cb)`.

core: list: allow `bf_list_ops` to be `NULL`

---

src/bpfilter/ctx.c
src/core/list.h

`bf_list_move()` moves a list from a variable to another. The moved source variable doesn't reference any data anymore and `bf_list_clean()` can be called on it safely. The moved to variable has to call `bf_list_clean()` to free the resources.

core: list: add `bf_list_move()` to safely move an initialized list

---

src/bpfilter/cgen/matcher/ip4.c

The IPv4 address mask defined in a matcher was applied to the reference address (also defined in the matcher), but not the IPv4 address in the packet.
Apply the mask to both the address in the matcher and in the packet before comparing them.

cgen: ip4: fix IPv4 mask support

---

.clang-tidy
doc/CMakeLists.txt
doc/developers/modules/core.rst
doc/developers/modules/index.rst
doc/usage/daemon.rst
src/bpfilter/cgen/cgen.c
src/bpfilter/cgen/cgen.h
src/bpfilter/ctx.c
src/bpfilter/ctx.h
src/bpfilter/main.c
src/bpfilter/xlate/cli.c
src/bpfilter/xlate/ipt/ipt.c
src/bpfilter/xlate/nft/nft.c
src/core/CMakeLists.txt
src/core/ns.c
src/core/ns.h
src/core/request.h
tests/e2e/netns.sh

Introduce `bf_ns` structure to represent the namespaces used by a client. This structure is stored in the request to be processed by the daemon. Then, before attaching the BPF program, the daemon will switch to the namespaces stored in the `bf_ns` object, and switch back to its original namespaces.
This change only allows `bpfilter` to attach BPF programs to the correct location according to the client's namespace, as well as filter on the expected interface. More changes will come to limit clients to the chains defined in their namespaces.
The documentation has been updated to reflect the changes, and `tests/netns.sh` has been added to validate the feature.
More details in the commit messages.

Add support for network and mount namespaces

---

tests/unit/CMakeLists.txt

The build system will always use lcov to generate `lcov.out` out of the `.gcda` and `.gcno` files after the unit tests are run. `lcov.out` will only be used during the documentation generation. Hence, there is no reason to generate `lcov.out` if `-DNO_DOCS=OFF` is defined.
Gate the generation of `lcov.out` (and the discovery of lcov binary) around the definition of `NO_DOCS` to ensure unit tests don't depend on lcov if `NO_DOCS=ON` is defined.

tests: unit: only generate `lcov.out` if docs are build

---

src/bfcli/parser.y

IPv4 addresses parsed by bfcli are converted into network byte order by default, but masks are not. Hence, as soon as a mask different from 32 is used, it is incorrectly applied.
Fix this bug by converting the IPv4 mask to network byte order.

cli: set IPv4 masks to network byte order

---

src/bpfilter/cgen/program.c

The set index a rule should filter on is stored in the fixup's attributes during generation. But `_bf_program_fixup()` uses the instruction's `imm` field as the set index, leading to bpfilter always using the file descriptor of set #0.
Fix `_bf_program_fixup()` by using the set index from the fixup attributes.

cgen: fix instructions using proper set index

---

.clang-tidy
.github/workflows/ci.yaml

Use Fedora 42 for CI, disable false positive clang-tidy options

---

doc/usage/iptables.rst

This PR fixes a small typo in the first line of the iptables.rst documentation file, changing 'build' to 'built'.

Fix typo in iptables.rst

---

doc/developers/modules/index.rst
src/bpfilter/cgen/program.h

Found some typos on the [website](https://bpfilter.io/) while reading the documentation
Here's a PR to fix them

Fix typos in documentation/website

---

src/bpfilter/cgen/program.c

`bpf/bpf.h` from libbpf is only included in `program.c` for `BPF_LOG_BUF_SIZE`. Copy it to `program.c` as `_BF_LOG_BUF_SIZE` instead and remove `#include <bpf/bpf.h>`.

daemon: do not include `bpf/bpf.h` in `program.c`

---

.clang-tidy
README.md
doc/usage/bfcli.rst
doc/usage/index.rst
src/bfcli/CMakeLists.txt
src/bfcli/chain.c
src/bfcli/chain.h
src/bfcli/helper.c
src/bfcli/helper.h
src/bfcli/main.c
src/bfcli/opts.c
src/bfcli/opts.h
src/bfcli/parser.y
src/bfcli/ruleset.c
src/bfcli/ruleset.h
src/bpfilter/cgen/program.c
src/core/hook.c
src/core/hook.h
tests/e2e/cli.sh
tools/benchmarks/benchmark.cpp

bfcli commands are composed of an object, an action, and options. Both the object and the action are required. Ruleset and chain commands currently implement different mechanism to parse the options, which requires a lot of duplicated code.
This refactor creates a generic framework to parse the bfcli commands in a standard way for all the commands supported by bpfilter.
Additionally, it adds support for bfcli-level help message, and command-level help message (e.g. bfcli chain set --help).
This PR is required by two changes requests (#252 and #249), both on bfcli options parsing. I reused most of @ryantimwilson 's documentation but implemented through argp, thanks to him!

cli: refactor the commands parser

---

.clang-tidy
.github/workflows/ci.yaml
doc/usage/daemon.rst
src/bpfilter/cgen/cgen.c
src/bpfilter/cgen/cgen.h
src/bpfilter/cgen/prog/link.c
src/bpfilter/cgen/program.c
src/bpfilter/cgen/program.h
src/bpfilter/ctx.c
src/bpfilter/ctx.h
src/bpfilter/main.c
src/bpfilter/opts.c
src/bpfilter/opts.h
src/bpfilter/xlate/cli.c
src/core/bpf.c
src/core/bpf.h
src/core/io.c
src/core/io.h
src/core/request.c
src/core/request.h
tests/e2e/cli.sh

Using the `--bpffs-path`, the user can change the location of the bpffs path used by the daemon. In a containerized environment (especially with userns), users might dedicate a specific bpffs for bpfilter, with support for BPF token.
The program pinning/unpinning logic has been removed from program.c into cgen.c, as cgen.c has access to both the old and new program on update. The tests have been updated to use a custom bpffs path and validate the implementation.

Customize bpffs path

---

.clang-tidy
src/bfcli/opts.c
src/bfcli/parser.y
src/bpfilter/opts.c
src/bpfilter/xlate/ipt/helpers.h
src/bpfilter/xlate/ipt/ipt.c
src/core/helper.h
src/core/hook.c
src/core/hook.h
tests/unit/bpfilter/opts.c

Create `BF_FLAGS(...)` macros to generate a bitflag values out of a list of integer representing the index of the bits to set.

core: helper: add `BF_FLAGS()` macro to generate bitflags

---

src/bfcli/main.c
src/bpfilter/main.c
src/bpfilter/opts.c

[argp](https://www.gnu.org/software/libc/manual/html_node/Argp.html) has a feature to autogenerate the `--version` flag using [global variables](https://www.gnu.org/software/libc/manual/html_node/Argp-Global-Variables.html)
This PR aims to replace the manual implementation in `bpfilter` and `bfcli` binairies with this feature

Use argp global variables to generate version flag in bpfilter and bfcli

---

doc/benchmarks.html.template
doc/benchreport
tools/benchmarks/benchmark.cpp
tools/benchmarks/benchmark.hpp
tools/benchmarks/main.cpp
tools/perfrec

It seems bfcli is slow to parse and load rulesets with a large set (this might be applicable to large rulesets in general, but I assume fixing one would fix the other).
This change introduces a benchmark for bfcli big set parsing and loading duration.

Add a benchmark for chain loading time

---

tests/unit/CMakeLists.txt

Unit tests use `-Wl,wrap` flag to wrap functions to mock (e.g. `bf_ctx_token()`). However, when GCC inlines small functions, some of those wrapped functions might be inlined, preventing the wrapping and mocking of it.
Build unit tests with `-fno-inline-small-functions` to prevent inlining of small functions.

Prevent wrapped functions from being inlined during unit tests

---

tests/unit/bpfilter/cgen/prog/map.c

The mocked bf_bpf_obj_get() call should return 0 as a success value, not 1.

Fix `map.marsh_unmarsh` unit test for `bf_bpf_obj_get()` mock to return the correct value

---

CMakeLists.txt
src/bfcli/CMakeLists.txt
src/bfcli/main.c
src/bpfilter/CMakeLists.txt
src/bpfilter/main.c

Use `argp_program_bug_address` to set the contact address for bfcli and bpfilter.

Set contact in bfcli and bpfilter help

---

doc/benchmarks.html.template

To extract meaningful signal from the benchmark results, update the benchmark page template to calculate the standard deviation and standard score of the last benchmark result compared to the average of the 10 results before it.

Compare last benchmark results to the average 10 last commits baseline

---

doc/benchmarks.html.template

Let's get Meta's copyright bot off my back.

Add missing copyright header to doc/benchmarks.html.template

---

tests/e2e/main.c
tests/harness/test.c
tests/harness/test.h
tests/unit/main.c

`__start_bf_test` and `__end_bf_test` are symbols defined at the beginning and end of the `bf_test` section, used to store the tests definition. Some compiler options (e.g. clang's `start-stop-gc`) will discard the `bf_test` section if it doesn't contain any code, triggering a build failure as the `__start` and `__stop` symbols are not defined.
To prevent this error, the `__start_bf_test` and `__stop_bf_test` symbols are not defined in harness anymore, but in the binary defining the tests, their address is passed to the test discovery function as a parameter.

Only declare `__start_bf_test` and `__stop_bf_test` in the test binaries, not the test harness

---

src/bpfilter/main.c
src/core/io.c
src/core/io.h
tests/e2e/CMakeLists.txt
tests/e2e/daemon.sh

bpfilter creates a socket file to listen to for incoming requests. When starting the dameon, if this file is already exists, the daemon stops, to prevent running the daemon twice. When the daemon stops, this file is removed. However, if the daemon crashes, the socket file is not removed and the daemon can't be restarted anymore.
Use a lock file to check if a daemon is already running: open and lock the file when the daemon starts. If the file is already locked, return an error. Once the lock is acquired, the daemon will will remove any existing socket file (as we're sure it's unused), and create a new one with bind().

Use a lock file to prevent the daemon from starting twice, or fail to start due to leftover socket file

---

src/bfcli/print.c
src/bpfilter/cgen/cgen.c
src/core/chain.c
tests/e2e/e2e.c
tests/e2e/e2e.h
tests/e2e/main.c
tests/harness/filters.h
tests/unit/CMakeLists.txt
tests/unit/core/chain.c

Set `rule->index` in `bf_chain_new()` and `bf_chain_new_from_marsh()`, otherwise the rules used in a program could have any index (valid or not), leading to counter issues.

Fix unset rule index

---

tools/benchmarks/benchmark.cpp
tools/benchmarks/benchmark.hpp
tools/benchmarks/main.cpp

Disable ASLR when running the benchmark to avoid unreproducible noise. See https://google.github.io/benchmark/reducing_variance.html

Disable ASLR during benchmarks

---

src/bfcli/ruleset.c
src/libbpfilter/bpfilter.h
src/libbpfilter/cli.c
tests/e2e/e2e.c
tests/harness/prog.c

Before chains can be manipulated by bfcli, libbpfilter's functions were named such as `bf_cli_*` as they were dedicated to the CLI. It's not true another, as they can be used by external programs.
Rename `bf_cli_*` function to `bf_*` instead, so the naming is consistent across the library.

Use a consistent naming scheme for libbpfilter's symbols

---

doc/benchreport

When generating the benchmark report, we expect the results to be displayed in the order their commit appear in the Git tree.
Update benchreport to sort the benchmarked commits according to the tree order.

Sort commit benchmark results according to the Git history order

---

src/bfcli/CMakeLists.txt
src/bfcli/helper.c
src/bfcli/lexer.l
src/core/helper.h
tools/benchmarks/main.cpp

Fix #257 
We noticed that loading large rulesets in bfcli took a long time, and after tracking it down, the solution to increase the `YY_READ_BUF_SIZE` was found.
Since we can't modify it directly, we use a compiler definition in `src/bfcli/CMakeLists.txt` to make it refer to a global variable that we can manipulate easily.
The current implementation of `compute_buf_size()` is extrapolated through tries and the [graph](https://github.com/facebook/bpfilter/issues/257#issuecomment-2891493844), it's implementation is heuristic and could be improved in the future.
Also we *could* add a lower/upper bound on the buffer size, but I don't know how useful that is.
The `build/bfcli/generated/bfcli/lexer.c` mention that "`YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case`".
But the code it's …

Dynamically compute `YY_READ_BUF_SIZE` to reduce time spent parsing large chains

---

doc/usage/bfcli.rst
src/bfcli/lexer.l
src/bpfilter/cgen/matcher/icmp.c
src/bpfilter/cgen/program.c
src/core/matcher.c
src/core/matcher.h
tests/e2e/cli.sh
tests/e2e/genpkts.py
tests/e2e/main.c
tests/rules.bpfilter

Issue #214 
bfcli and bpfilter now support ICMPv6 type and code.
e2e tests have been added. cli tests were excluded as they currently appear not to support IPv6.
Minimal update of ruleset file.

cli,daemon: add support for icmpv6.type and icmpv6.code

---

src/bpfilter/CMakeLists.txt
src/bpfilter/bpf/update_counters.bpf.c
src/bpfilter/cgen/elfstub.c
src/bpfilter/cgen/elfstub.h
src/bpfilter/cgen/fixup.c
src/bpfilter/cgen/fixup.h
src/bpfilter/cgen/program.c
src/bpfilter/cgen/program.h
src/bpfilter/cgen/stub.c
tests/unit/CMakeLists.txt
tests/unit/bpfilter/cgen/program.c

Improve ELF parsing to allow ELF stubs to use `bpf_printk()`. `bpf_printk()` calls are relocated like any kfunc call, but the format string is copied from the `.rodata` section for the ELF file and put into a BPF map, similarly to `EMIT_PRINT()`.
As `bpf_printk()` is now supported, the function generated to update counters has been replaced by an ELF stub. All the `bf_program` pieces related to function have also been removed, and ELF stub is used exclusively now.

Support `bpf_printk()` in ELF stubs

---

src/bpfilter/cgen/prog/map.c
src/bpfilter/cgen/prog/map.h
src/bpfilter/cgen/program.c
src/core/set.c
src/core/set.h

`set.c` defines a function to convert a set type into a BPF map type, which requires the map types defined in `map.h`. Hence, it creates a dependency from the core module to the bpfilter module, which is an error.
Move the function to convert a set type into a BPF map type into map.c to remove the dependency.

Remove the dependency of the `core` module to the `bpfilter` module

---

src/bfcli/print.c

bfcli will print a 'counters ...' line for every rule when printing a chain or the ruleset, even if the rule doesn't have counters enabled.
Check if the rule has counters enabled before printing it.

Do not print counters for rules with counters disabled

---

src/bpfilter/cgen/matcher/ip6.c

Defining `uint8_t eh_mask` within a switch..case statement can trigger build errors depending on the compiler flags.
Define `eh_mask` at the begining of the function to prevent build errors.

Preventing build errors due to a variable being defined in a `switch..case` statement

---

tools/cmake/ElfStubs.cmake

Update the sed command to properly rename the symbols exported by xxd during ELF stubs generation.

Fix command to rename xxd symbols

---

src/bpfilter/cgen/cgen.c
tests/e2e/cli.sh

`bf_cgen_update()` unpin the old program, before updating the link, and pinning the old program back. Obviously, we need to pin the new program, not the old one.
This commit pin the new program and add end-to-end tests to validate the update has been performed correctly.

On chain update, pin the new program, not the old one

---

doc/usage/bfcli.rst
src/bfcli/lexer.l
src/bfcli/parser.y
src/bfcli/print.c
src/core/set.c
src/core/set.h
tests/e2e/cli.sh
tests/harness/filters.c
tests/rules.bpfilter
tests/unit/core/set.c

Currently, users can use sets to efficiently filter packets against a large pool of similarly formatted data. Sets are defined as part of a rule, and can't be reused for other rules. If a user wants to filter on the same 10k elements sets in 2 different rules, bpfilter will create the set twice.
This change adds a new syntax to allow users to create named sets at the beginning of a chain, then filter on it in a rule using its name:
```
chain mychain BF_HOOK_XDP{ifindex=2} ACCEPT
set myset (ip4.saddr, ip4.proto) in {
192.168.1.1, udp;
192.168.1.1, tcp
}
rule
(ip4.saddr, ip4.proto) in myset
tcp.flags any syn
counter
ACCEPT
rule
(ip4.saddr, ip4.proto) in myset
counter
ACCEPT
```

Allow users to name and reuse sets

---

doc/usage/bfcli.rst
src/bpfilter/cgen/matcher/meta.c
src/bpfilter/cgen/matcher/tcp.c
src/bpfilter/cgen/matcher/udp.c
src/libbpfilter/include/bpfilter/matcher.h
src/libbpfilter/matcher.c
tests/e2e/main.c
tests/rules.bpfilter

Allow users to use `tcp.(d|s)port` and `udp.(d|s)port` in sets by adding support for `BF_MATCHER_IN` operators. This change requires their payload to be stored in big-endian format, so it doesn't have to be converted when stored in a BPF map.

Allow `tcp.(d|s)port` and `udp.(d|s)port` in sets

---

src/bpfilter/main.c

If a failure occurs during request processing, the daemon should print an error message and process the next request. It should not be possible to put the daemon in a failure state from a failing request, so there is no reason for the daemon to stop.

Nicely handle errors when processing requests

---

doc/usage/bfcli.rst

Sets require the key to be defined in parentheses, since f71a1b4, fix the documentation to reflect this.

doc: fix erroneous set examples

---

doc/usage/bfcli.rst
src/bfcli/lexer.l
src/bfcli/parser.y
src/bpfilter/cgen/cgen.c
src/bpfilter/cgen/cgroup.c
src/bpfilter/cgen/matcher/meta.c
src/bpfilter/cgen/nf.c
src/bpfilter/cgen/program.c
src/bpfilter/cgen/tc.c
src/libbpfilter/chain.c
src/libbpfilter/include/bpfilter/chain.h
src/libbpfilter/include/bpfilter/flavor.h
src/libbpfilter/include/bpfilter/matcher.h
src/libbpfilter/include/bpfilter/rule.h
src/libbpfilter/matcher.c
src/libbpfilter/rule.c
tests/e2e/cli.sh
tests/e2e/e2e.c
tests/e2e/main.c
tests/rules.bpfilter

Add the new `mark` rule keyword to mark a matched packet. The mark is set in the `sk_buff` structure, and can be matched on later on by a `meta.mark` matcher, or outstide bpfilter with a TC filter.

cli,lib,daemon: support packet marking and add meta.mark matcher

---

src/bfcli/print.c
src/bpfilter/bpf/log.bpf.c
src/libbpfilter/include/bpfilter/runtime.h

`bf_log` stores the L3 header identifier in network byteorder, which requires the user to convert it. Use `bpf_ntohs()` to store the L3 header identifier into the log structure.
The various packet headers are left unchanged.

lib,cli,daemon: store log fields in host byteorder
